# THIS FILE IS GENERATED BY antigen-hs!!!!

source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-environment/environment.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-terminal/terminal.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-editor/editor.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-history/history.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-directory/directory.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-spectrum/spectrum.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-helper/helper.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-gnu-utility/gnu-utility.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-utility/utility.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-completion/completion.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-archive/archive.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-fasd/fasd.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-git/git.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-osx/osx.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-ssh/ssh.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-prompt/prompt.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-tmux/tmux.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-rsync/rsync.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-secrets/secrets.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-zmv/zmv.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-gvm/gvm.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-nodenv/nodenv.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-rvm/rvm.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-grc/grc.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-java/java.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-python/python.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-direnv/direnv.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-homebrew/homebrew.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-perl/perl.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-screen/screen.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-dpkg/dpkg.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-command-not-found/command-not-found.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-mcd/mcd.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search/zsh-history-substring-search.plugin.zsh

fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-environment
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-terminal
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-editor
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-history
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-directory
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-spectrum
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-helper
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-gnu-utility
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-utility
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-completion
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-archive
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-fasd
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-git
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-osx
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-ssh
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-prompt
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-tmux
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-rsync
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-secrets
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-zmv
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-gvm
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-nodenv
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-rvm
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-grc
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-java
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-python
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-direnv
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-homebrew
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-perl
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-screen
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-joshuarubin-SLASH-zsh-dpkg
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-command-not-found
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-mcd
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting
fpath+=/Users/jrubin/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search

