source $ZSH/zsh/bundles/joshuarubin/zsh-environment/environment.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-terminal/terminal.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-editor/editor.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-history/history.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-directory/directory.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-spectrum/spectrum.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-helper/helper.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-completion/completion.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-archive/archive.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-fasd/fasd.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-git/git.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-osx/osx.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-ssh/ssh.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-prompt/prompt.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-tmux/tmux.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-rsync/rsync.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-secrets/secrets.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-zmv/zmv.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-gvm/gvm.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-nodenv/nodenv.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-rvm/rvm.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-grc/grc.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-java/java.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-python/python.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-direnv/direnv.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-homebrew/homebrew.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-perl/perl.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-screen/screen.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-dpkg/dpkg.plugin.zsh
source $ZSH/zsh/bundles/Tarrasch/zsh-command-not-found/command-not-found.plugin.zsh
source $ZSH/zsh/bundles/Tarrasch/zsh-mcd/mcd.plugin.zsh
source $ZSH/zsh/bundles/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source $ZSH/zsh/bundles/zsh-users/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-gnu-utility/gnu-utility.plugin.zsh
source $ZSH/zsh/bundles/joshuarubin/zsh-utility/utility.plugin.zsh

fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-environment
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-terminal
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-editor
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-history
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-directory
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-spectrum
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-helper
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-completion
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-archive
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-fasd
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-git
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-osx
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-ssh
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-prompt
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-tmux
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-rsync
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-secrets
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-zmv
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-gvm
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-nodenv
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-rvm
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-grc
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-java
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-python
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-direnv
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-homebrew
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-perl
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-screen
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-dpkg
fpath+=$ZSH/zsh/bundles/Tarrasch/zsh-command-not-found
fpath+=$ZSH/zsh/bundles/Tarrasch/zsh-mcd
fpath+=$ZSH/zsh/bundles/zsh-users/zsh-syntax-highlighting
fpath+=$ZSH/zsh/bundles/zsh-users/zsh-history-substring-search
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-gnu-utility
fpath+=$ZSH/zsh/bundles/joshuarubin/zsh-utility
